# Copyright (c) 2024, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms and conditions of the GNU General Public License,
# version 2, as published by the Free Software Foundation.
#
# This program is distributed in the hope it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.

%YAML 1.2
---
$id: http://devicetree.org/schemas/SS_ErrorReportingConfig/nvidia,tegra-SafetyServiceConfig.yaml#
$schema: http://devicetree.org/meta-schemas/core.yaml#

title: Nvidia Safety Service Configuration

maintainers:
  - Rahul Bedarkar

description: |
     The following nodes use this compatibility
        - /SS_ErrorReportingConfig

select:
  properties:
    compatible:
        minItems: 1
        maxItems: 1
        items:
            enum:
                - nvidia,tegra-SafetyServiceConfig

  required:
    - compatible

properties:

    Sw_Errors_count:
        $ref: "/schemas/types.yaml#/definitions/uint32"
        minimum: 0x1
        maximum: 0x1

    Sw_Errors:
        $ref: "/schemas/types.yaml#/definitions/uint32"
        minimum: 0x30
        maximum: 0x8120

    TSC_MON_Enable:
        $ref: "/schemas/types.yaml#/definitions/uint32"
        minimum: 0x1
        maximum: 0x1

    TSC_MON_Drift_Threshold:
        $ref: "/schemas/types.yaml#/definitions/uint32"
        minimum: 0x64
        maximum: 0x64

    TSC_MON_Debounce_Delay:
        $ref: "/schemas/types.yaml#/definitions/uint32"
        minimum: 0x1388
        maximum: 0x1388

    TSC_MON_Sync_Timeout:
        $ref: "/schemas/types.yaml#/definitions/uint32"
        minimum: 0x2710
        maximum: 0x2710

required:
    - compatible

examples:
    - |
        SS_ErrorReportingConfig {
        };
