# Copyright (c) 2024, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms and conditions of the GNU General Public License,
# version 2, as published by the Free Software Foundation.
#
# This program is distributed in the hope it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.

%YAML 1.2
---
$id: http://devicetree.org/schemas/tegra-isp-map/nvidia,csi-isp-map-config.yaml#
$schema: http://devicetree.org/meta-schemas/core.yaml#

title: Nvidia Tegra CSI-ISP Map Config

maintainers:
  - Chinniah Poosapadi

description: |
     The following nodes use this compatibility
        - /tegra-isp-map

select:
  properties:
    compatible:
        minItems: 1
        maxItems: 1
        items:
            enum:
                - nvidia,csi-isp-map-config

  required:
    - compatible

properties:

    nvidia,isp-mapping:
        $ref: "/schemas/types.yaml#/definitions/uint32-matrix"
        items:
            minItems: 2
            maxItems: 2
            items:
                - $ref: "/schemas/types.yaml#/definitions/uint32"
                  minimum: 0x0
                  maximum: 0x5
                - $ref: "/schemas/types.yaml#/definitions/uint32"
                  minimum: 0x0
                  maximum: 0x1

required:
    - compatible

examples:
    - |
        tegra-isp-map {
            compatible = "nvidia,csi-isp-map-config";
            nvidia,isp-mapping = <0 0>,
                                 <1 0>,
                                 <2 1>,
                                 <3 1>,
                                 <4 0>,
                                 <5 1>;
            status = "disabled";
        };
