#SPDX-License-Identifier: GPL-2.0-only
#Copyright (c) 2024, NVIDIA Corporation.  All rights reserved.

version = "1.0.0"

#Filter out all packages for NSPECT-2SC5-5SJZ program ONLY
[[oss.excluded.directories]]
paths = ['drivers/block/',
         'drivers/bus/',
         'drivers/clk/',
         'drivers/devfreq/',
         'drivers/gpu/',
         'drivers/mfd/',
         'drivers/net/',
         'drivers/nvpps/',
         'drivers/pinctrl/',
         'drivers/pwm/',
         'drivers/reset/',
         'drivers/soc/',
         'drivers/tty/',
         'drivers/virt/',
         'drivers/bluetooth/',
         'drivers/c2c/',
         'drivers/cpuidle/',
         'drivers/firmware/',
         'drivers/hwmon/',
         'drivers/media/',
         'drivers/misc/',
         'drivers/nv-p2p/',
         'drivers/nv-virtio/',
         'drivers/platform/',
         'drivers/ras/',
         'drivers/rtc/',
         'drivers/spi/',
         'drivers/usb/',
         'drivers/watchdog/',
         'drivers/bmi088/',
         'drivers/clink/',
         'drivers/crypto/',
         'drivers/gpio/',
         'drivers/i2c/',
         'drivers/memory/',
         'drivers/mtd/',
         'drivers/nvpmodel/',
         'drivers/pci/',
         'drivers/power/',
         'drivers/regulator/',
         'drivers/scsi/',
         'drivers/thermal/',
         'drivers/video/tegra/camera/',
         'drivers/video/tegra/dc/',
         'drivers/video/tegra/host/capture/',
         'drivers/video/tegra/host/isp/',
         'drivers/video/tegra/host/nvcsi/',
         'drivers/video/tegra/host/nvdla/',
         'drivers/video/tegra/host/vi/',
         'drivers/video/tegra/nvmap/',
         'drivers/video/tegra/tsec/',
         'drivers/video/tegra/virt/',
         'Documentation/',
         'include/',
         'configs/',
         'scripts/',
         'sound/',
         'tools/']
comment = 'Not used by PVA  or not used by PVA in Production'
nspect_ids = ['NSPECT-2SC5-5SJZ']

#Filter out all packages for NSPECT-86XH-KQRC program ONLY
[[oss.excluded.directories]]
paths = ['drivers/block/',
         'drivers/bus/',
         'drivers/clk/',
         'drivers/devfreq/',
         'drivers/gpu/',
         'drivers/mfd/',
         'drivers/net/',
         'drivers/nvpps/',
         'drivers/pinctrl/',
         'drivers/pwm/',
         'drivers/reset/',
         'drivers/soc/',
         'drivers/tty/',
         'drivers/virt/',
         'drivers/bluetooth/',
         'drivers/c2c/',
         'drivers/cpuidle/',
         'drivers/firmware/',
         'drivers/hwmon/',
         'drivers/media/',
         'drivers/misc/',
         'drivers/nv-p2p/',
         'drivers/nv-virtio/',
         'drivers/platform/',
         'drivers/ras/',
         'drivers/rtc/',
         'drivers/spi/',
         'drivers/usb/',
         'drivers/watchdog/',
         'drivers/bmi088/',
         'drivers/clink/',
         'drivers/crypto/',
         'drivers/gpio/',
         'drivers/i2c/',
         'drivers/memory/',
         'drivers/mtd/',
         'drivers/nvpmodel/',
         'drivers/pci/',
         'drivers/power/',
         'drivers/regulator/',
         'drivers/scsi/',
         'drivers/thermal/',
         'drivers/video/tegra/camera/',
         'drivers/video/tegra/host/',
         'drivers/video/tegra/nvmap/',
         'drivers/video/tegra/tsec/',
         'drivers/video/tegra/virt/',
         'Documentation/',
         'include/',
         'configs/',
         'scripts/',
         'sound/',
         'tools/']
comment = 'Unused packages in Display Serdes'
nspect_ids = ['NSPECT-86XH-KQRC']
